version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestTuesJulProject
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.testtuesjul.integrations:Call_TPPService
  packages:
  - name: TestTuesJulProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: services:add3Ints
  packages:
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.7
- serviceName: project.testtuesjul.integrations:Call_ref1
  packages:
  - name: TestTuesJulProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.testtuesjul.referencedata:ref1
  packages:
  - name: TestTuesJulProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
